"use strict";

const fixtures = {
  AAPL: { name: "Apple", price: "$187.40", priceNote: "Synthetic reference · no market feed", posture: "WATCH", confidence: "Research confidence: 62 / 100", evidenceHealth: "4 / 4", evidenceNote: "Synthetic evidence items available", risk: "MODERATE", riskNote: "Fixture-defined scenario range", events: [["Product", "Example: product-cycle discussion", "Company-specific · synthetic"], ["Regulation", "Example: policy uncertainty noted", "Company-specific · synthetic"], ["Macro", "Example: rate-sensitive demand context", "Broad-market · synthetic"], ["Earnings", "Example: reporting-window reminder", "Company-specific · synthetic"]], scenarios: [["Constructive", "What if demand remains resilient while costs stay controlled?"], ["Base case", "What if growth and margins remain near fixture assumptions?"], ["Cautious", "What if demand, policy, or supply conditions deteriorate?"]] },
  MSFT: { name: "Microsoft", price: "$421.15", priceNote: "Synthetic reference · no market feed", posture: "RESEARCH", confidence: "Research confidence: 66 / 100", evidenceHealth: "3 / 3", evidenceNote: "Synthetic evidence items available", risk: "MODERATE", riskNote: "Fixture-defined scenario range", events: [["Earnings", "Example: cloud-segment reporting context", "Company-specific · synthetic"], ["Product", "Example: product roadmap item", "Company-specific · synthetic"], ["Regulation", "Example: competition-policy context", "Company-specific · synthetic"]], scenarios: [["Constructive", "What if enterprise demand broadens?"], ["Base case", "What if growth normalizes as expected?"], ["Cautious", "What if enterprise spending slows?"]] },
  NVDA: { name: "NVIDIA", price: "$862.70", priceNote: "Synthetic reference · no market feed", posture: "WATCH", confidence: "Research confidence: 59 / 100", evidenceHealth: "3 / 3", evidenceNote: "Synthetic evidence items available", risk: "ELEVATED", riskNote: "Fixture-defined scenario range", events: [["Product", "Example: platform roadmap context", "Company-specific · synthetic"], ["Macro", "Example: infrastructure-spending context", "Broad-market · synthetic"], ["Guidance", "Example: forward-looking commentary context", "Company-specific · synthetic"]], scenarios: [["Constructive", "What if infrastructure spending exceeds assumptions?"], ["Base case", "What if demand follows fixture assumptions?"], ["Cautious", "What if concentration or supply constraints rise?"]] }
};
const checks = ["No network calls or external APIs", "No account, portfolio, or brokerage connection", "No personal data collection or persistence", "No investment instruction or execution capability"];
const byId = id => document.getElementById(id);
function render() { const data = fixtures[byId("ticker").value]; byId("posture").textContent = data.posture; byId("confidence").textContent = data.confidence; byId("price").textContent = data.price; byId("price-note").textContent = data.priceNote; byId("evidence-health").textContent = data.evidenceHealth; byId("evidence-note").textContent = data.evidenceNote; byId("risk").textContent = data.risk; byId("risk-note").textContent = data.riskNote; byId("timeline").replaceChildren(...data.events.map(([label,title,meta]) => { const li=document.createElement("li"); li.innerHTML=`<div class="event-top"><span>${label}</span><span class="chip">Fixture</span></div><p>${title}</p><p class="event-meta">${meta}</p>`; return li;})); byId("checks").replaceChildren(...checks.map(text => {const li=document.createElement("li");li.textContent=text;return li;})); byId("scenarios").replaceChildren(...data.scenarios.map(([title,text]) => {const article=document.createElement("article");article.className="scenario";article.innerHTML=`<h3>${title}</h3><p>${text}</p>`;return article;})); byId("data-status").textContent=`${data.name} fixture loaded locally · no network activity`; }
byId("ticker").addEventListener("change", render); byId("refresh").addEventListener("click", render); render();
